# Vector_Windows_Defender_MPLogs_Mplog-Parser_OriginalFilename config.
# Description: Process Windows Defender MPLogs OriginalFilename artefacts parsed with Mplog-Parser (CSV output).
#              For more information on Windows Defender Microsoft Protection Log (MPLog): https://artefacts.help/windows_defender_support_logs.html
#              Filename should match: "*MPLog_OriginalFilename*.csv"
#              source = "windows_mplog_originalfilename" & sourcetype = "windows_artefact"
# Author(s): Thomas DIOT (Qazeer)
# Version: 1.0
# Last modified: 2024-03-23
# Required environment variables:
#   INPUT_FOLDER = "<INPUT_FOLDER>"
#   VECTOR_TEMP_FOLDER = "<VECTOR_TEMP_FOLDER>"
#   SOURCE_HOST = "<SOURCE_HOST>"

# Temporary folder used by Vector.
data_dir = "${VECTOR_TEMP_FOLDER:?A directory for Vector temporary data is required}"

# Set the default timezone to UTC+0 for timestamps that do not include a timezone.
timezone = "Etc/UTC"

[sources.MPLog_Mplog-Parser_OriginalFilename_csv_input]
  type = "file"
  include = ["${INPUT_FOLDER:?The input folder containing the Windows Defender MPLog files is required.}/*/Antivirus/*MPLog_OriginalFilename*.csv"]
  ignore_checkpoints = true
  read_from = "beginning"
  oldest_first = false
  glob_minimum_cooldown_ms = 100000
  fingerprint.strategy = "device_and_inode"
  max_line_bytes = 100_000_000
  offset_key = "__offset"
  encoding.charset = "utf-16le"

[transforms.MPLog_Mplog-Parser_OriginalFilename_csv_parser_to_sink]
  type = "remap"
  inputs = ["MPLog_Mplog-Parser_OriginalFilename_csv_input"]
  source = '''
    # Expect CSV header:
    # timestamp,original_filename,full_path
    fields, err = parse_csv(.message, delimiter: ",")
    if err != null {
      log("Unable to split CSV: " + err, level: "error")
    }

    if .__offset == 0 {
      expected_header = "timestamp,original_filename,full_path"
      current_header = strip_whitespace(string!(.message))
      if expected_header != current_header {
        log("Unexpected CSV header, possible non-integrated tool update!\n=> Expected CSV header: " + expected_header + "\n=> Got CSV header:      " + current_header, level: "error")
      }
      abort
    }

    .timestamp = parse_timestamp(fields[0], format: "%+") ?? fields[0]
    .original_filename = fields[1]
    .full_path = fields[2]

    # Add the metadata fields following the parsing.
    .sourcehost = "${SOURCE_HOST:?The source host is required}"
    .host = .sourcehost
    .category = "detection"
    .source = "windows_mplog_originalfilename"
    .sourcetype = "windows_artefact"

    # Delete irrelevant default fields.
    del(.source_type)
    del(.file)
    del(.message)
    del(.__offset)
  '''
