# Vector_Windows_EZTools_AmcacheParser_AmCache-File-Entries config.
# Description: Process Windows artefacts parsed with AmcacheParser (CSV output).
#              Filename should match: "*Amcache_AssociatedFileEntries.csv" and "*Amcache_UnassociatedFileEntries.csv"
#              AmcacheParser command: AmcacheParser.exe -f %sourceFile% --csv %destinationDirectory% -i
#              Example command: AmcacheParser.exe -f "C:\Windows\appcompat\Programs\Amcache.hve" --csv <YOUR_OUTPUT>
#              source = "windows_amcache-associatedfileentries|windows_amcache-unassociatedfileentries" & sourcetype = "windows_artefact"
# Author(s): Jérôme BREBION, Thomas DIOT (_Qazeer)
# Version: 1.0
# Last modified: 2022-09-28
# Required environment variables:
#   INPUT_FOLDER = "<INPUT_FOLDER>"
#   VECTOR_TEMP_FOLDER = "<VECTOR_TEMP_FOLDER>"
#   SOURCE_HOST = "<SOURCE_HOST>"

# Temporary folder used by Vector.
data_dir = "${VECTOR_TEMP_FOLDER:?A directory for Vector temporary data is required}"

# Set the default timezone to UTC+0 for timestamps that do not include a timezone.
timezone = "Etc/UTC"

[sources.AmcacheParser_AmCache-File-Entries_csv_input]
  type = "file"
  include = [
    "${INPUT_FOLDER:?The input folder containing the AmcacheParser AmCache Associated File Entries files is required.}/*/ProgramExecution/*Amcache_AssociatedFileEntries.csv",
    "${INPUT_FOLDER:?The input folder containing the AmcacheParser AmCache Unassociated File Entries files is required.}/*/ProgramExecution/*Amcache_UnassociatedFileEntries.csv"
  ]
  ignore_checkpoints = true
  read_from = "beginning"
  oldest_first = false
  glob_minimum_cooldown_ms = 100000
  fingerprint.strategy = "device_and_inode"
  max_line_bytes = 100_000_000
  offset_key = "__offset"

[transforms.AmcacheParser_AmCache-File-Entries_csv_parser]
  type = "remap"
  inputs = ["AmcacheParser_AmCache-File-Entries_csv_input"]
  source = '''
    # Expect CSV headers:
    # ApplicationName,ProgramId,FileKeyLastWriteTimestamp,SHA1,IsOsComponent,FullPath,Name,FileExtension,LinkDate,ProductName,Size,Version,ProductVersion,LongPathHash,BinaryType,IsPeFile,BinFileVersion,BinProductVersion,Usn,Language,Description
    # ProgramName,ProgramID,VolumeID,VolumeIDLastWriteTimestamp,FileID,FileIDLastWriteTimestamp,SHA1,FullPath,FileExtension,MFTEntryNumber,MFTSequenceNumber,FileSize,FileVersionString,FileVersionNumber,FileDescription,SizeOfImage,PEHeaderHash,PEHeaderChecksum,BinProductVersion,BinFileVersion,LinkerVersion,BinaryType,IsLocal,GuessProgramID,Created,LastModified,LastModifiedStore,LinkDate,LanguageID,ProductName,CompanyName,SwitchBackContext
    fields, err = parse_csv(.message, delimiter: ",")
    if err != null {
      log("Unable to split CSV: " + err, level: "error")
    }

    if .__offset == 0 {
      expected_header_older_amcache = "ApplicationName,ProgramId,FileKeyLastWriteTimestamp,SHA1,IsOsComponent,FullPath,Name,FileExtension,LinkDate,ProductName,Size,Version,ProductVersion,LongPathHash,BinaryType,IsPeFile,BinFileVersion,BinProductVersion,Usn,Language,Description"
      expected_header_recent_amcache = "ProgramName,ProgramID,VolumeID,VolumeIDLastWriteTimestamp,FileID,FileIDLastWriteTimestamp,SHA1,FullPath,FileExtension,MFTEntryNumber,MFTSequenceNumber,FileSize,FileVersionString,FileVersionNumber,FileDescription,SizeOfImage,PEHeaderHash,PEHeaderChecksum,BinProductVersion,BinFileVersion,LinkerVersion,BinaryType,IsLocal,GuessProgramID,Created,LastModified,LastModifiedStore,LinkDate,LanguageID,ProductName,CompanyName,SwitchBackContext"
      current_header = strip_whitespace(string!(.message))
      if current_header != expected_header_older_amcache && current_header != expected_header_recent_amcache {
        log("Unexpected CSV header, possible non-integrated tool update!\n=> Expected CSV headers: " + expected_header_older_amcache + "\n or " + expected_header_recent_amcache + "\n=> Got CSV header:      " + current_header, level: "error")
      }
      abort
    }

    if length(fields) == 21 {
      .applicationname = fields[0]
      .programid = fields[1]
      .filekeylastwritetimestamp = fields[2]
      .sha1 = fields[3]
      .isoscomponent = fields[4]
      .fullpath = fields[5]
      .name = fields[6]
      .fileextension = fields[7]
      .linkdate = fields[8]
      .productname = fields[9]
      .size = fields[10]
      .version = fields[11]
      .productversion = fields[12]
      .longpathhash = fields[13]
      .binarytype = fields[14]
      .ispefile = fields[15]
      .binfileversion = fields[16]
      .binproductversion = fields[17]
      .usn = fields[18]
      .language = fields[19]
      .description = fields[20]

      .exe = .fullpath
      .timestamp = .filekeylastwritetimestamp

    } else if length(fields) == 32 {
      .programname = fields[0]
      .programid = fields[1]
      .volumeid = fields[2]
      .volumeidlastwritetimestamp = fields[3]
      .fileid = fields[4]
      .fileidlastwritetimestamp = fields[5]
      .sha1 = fields[6]
      .fullpath = fields[7]
      .fileextension = fields[8]
      .mftentrynumber = fields[9]
      .mftsequencenumber = fields[10]
      .filesize = fields[11]
      .fileversionstring = fields[12]
      .fileversionnumber = fields[13]
      .filedescription = fields[14]
      .sizeofimage = fields[15]
      .peheaderhash = fields[16]
      .peheaderchecksum = fields[17]
      .binproductversion = fields[18]
      .binfileversion = fields[19]
      .linkerversion = fields[20]
      .binarytype = fields[21]
      .islocal = fields[22]
      .guessprogramid = fields[23]
      .created = fields[24]
      .lastmodified = fields[25]
      .lastmodifiedstore = fields[26]
      .linkdate = fields[27]
      .languageid = fields[28]
      .productname = fields[29]
      .companyname = fields[30]
      .switchbackcontext = fields[31]

      .exe = .fullpath
      .timestamp = .fileidlastwritetimestamp

    } else {
      log("Unexpected number of parsed fields", level: "error")
    }

    if is_nullish(.timestamp) {
      log("Timestamp is null for event, defaulting to current time.", level: "warn")
      .timestamp = now()
    }

    if (contains!(.file, "Amcache_AssociatedFileEntries.csv")) {
        .source = "windows_amcache-associatedfileentries"
    } else if (contains!(.file, "Amcache_UnassociatedFileEntries.csv")) {
        .source = "windows_amcache-unassociatedfileentries"
    }

    # Add the metadata fields following the parsing.
    .sourcehost = "${SOURCE_HOST:?The source host is required}"
    .host = .sourcehost
    .category = "execution"
    .sourcetype = "windows_artefact"

    # Delete irrelevant default fields.
    del(.source_type)
    del(.file)
    del(.message)
    del(.__offset)
  '''

[transforms.AmcacheParser_AmCache-File-Entries_coerce]
  type = "remap"
  inputs = ["AmcacheParser_AmCache-File-Entries_csv_parser"]
  source = '''
    . = map_values(.) -> |value| {
      value_string, convert_err = string(value)
      # Only coerce string (and not already casted types, such as int, timestamps, etc.).
      if convert_err != null {
        value
      # Matches a timestamp in various format ("T" or space separated, with or without post second precision, and with or without a timezone identifier).
      } else if (match(value_string, r'^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[0-1])[T|\s]([01][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9])(\.[0-9]{1,9})?(\s?[\+|\-]([01][0-9]|2[0-4]):?([0-5][0-9]))?$')) {
        tmp_value = parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S%z") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%z") ?? parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S%.f%z") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%.f%z") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%.f %z") ?? parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S") ?? parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S%.f") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%.f") ?? value_string
        if is_string(tmp_value) {
          log("Failed to convert timestamp: " + value_string, level: "warn")
          value
        } else {
          tmp_value
        }
      } else if (tmp_value, err = parse_int(value); err == null) {
        tmp_value
      } else if (tmp_value, err = to_bool(value); err == null) {
        tmp_value
      } else if (tmp_value, err = to_float(value); err == null) {
        tmp_value
      } else {
        value
      }
    }
  '''

[transforms.AmcacheParser_AmCache-File-Entries_filekeylastwritetimestamp_to_sink]
  type = "remap"
  inputs = ["AmcacheParser_AmCache-File-Entries_coerce"]
  source = '''
    if is_nullish(.filekeylastwritetimestamp) {
      abort
    }

    .timestamp = .filekeylastwritetimestamp
    .operation = "filekeylastwritetimestamp"
    .suboperation = "filekeylastwritetimestamp"
  '''

[transforms.AmcacheParser_AmCache-File-Entries_volumeidlastwritetimestamp_to_sink]
  type = "remap"
  inputs = ["AmcacheParser_AmCache-File-Entries_coerce"]
  source = '''
    if is_nullish(.volumeidlastwritetimestamp) {
      abort
    }

    .timestamp = .volumeidlastwritetimestamp
    .operation = "volumeidlastwritetimestamp"
    .suboperation = "volumeidlastwritetimestamp"
  '''

[transforms.AmcacheParser_AmCache-File-Entries_fileidlastwritetimestamp_to_sink]
  type = "remap"
  inputs = ["AmcacheParser_AmCache-File-Entries_coerce"]
  source = '''
    if is_nullish(.fileidlastwritetimestamp) {
      abort
    }

    .timestamp = .fileidlastwritetimestamp
    .operation = "fileidlastwritetimestamp"
    .suboperation = "fileidlastwritetimestamp"
  '''

[transforms.AmcacheParser_AmCache-File-Entries_lastmodifiedstore_to_sink]
  type = "remap"
  inputs = ["AmcacheParser_AmCache-File-Entries_coerce"]
  source = '''
    if is_nullish(.lastmodifiedstore) {
      abort
    }

    .timestamp = .lastmodifiedstore
    .operation = "lastmodifiedstore"
    .suboperation = "lastmodifiedstore"
  '''
