# Vector_Windows_EZTools_SumECmd_UAL_DnsInfo config.
# Description: Process Windows User Access Logs artefacts parsed with SumECmd (CSV output) for DNS information.
#              Filename should match: "*SumECmd*DnsInfo*.csv"
#              SumECmd command: SumECmd.exe -d %sourceDirectory%\Windows\System32\LogFiles\SUM --csv %destinationDirectory%
#              source = "windows_ual-dnsinfo" & sourcetype = "windows_artefact"
# Author(s): Thomas DIOT (_Qazeer)
# Version: 1.0
# Last modified: 2022-09-28
# Required environment variables:
#   INPUT_FOLDER = "<INPUT_FOLDER>"
#   VECTOR_TEMP_FOLDER = "<VECTOR_TEMP_FOLDER>"
#   SOURCE_HOST = "<SOURCE_HOST>"

# Temporary folder used by Vector.
data_dir = "${VECTOR_TEMP_FOLDER:?A directory for Vector temporary data is required}"

# Set the default timezone to UTC+0 for timestamps that do not include a timezone.
timezone = "Etc/UTC"

[sources.SumECmd_UAL_DnsInfo_csv_input]
  type = "file"
  include = ["${INPUT_FOLDER:?The input folder containing the UAL DnsInfo file(s) is required.}/*/SUM/**/*SumECmd*DnsInfo*.csv"]
  ignore_checkpoints = true
  read_from = "beginning"
  oldest_first = false
  glob_minimum_cooldown_ms = 100000
  fingerprint.strategy = "device_and_inode"
  max_line_bytes = 100_000_000
  offset_key = "__offset"

[transforms.SumECmd_UAL_DnsInfo_csv_parser]
  type = "remap"
  inputs = ["SumECmd_UAL_DnsInfo_csv_input"]
  source = '''
    # Expect CSV header:
    # HostName,Address,LastSeen,SourceFile
    fields, err = parse_csv(.message, delimiter: ",")
    if err != null {
      log("Unable to split CSV: " + err, level: "error")
    }

    if .__offset == 0 {
      # Special usecase as the header line may (or may not) start with 'M-oM-;M-?' (UTF-8 with BOM).
      expected_header = "HostName,Address,LastSeen,SourceFile"
      current_header = strip_whitespace(string!(.message))
      header_find = find(current_header, expected_header)
      if header_find == -1 || (header_find != 0 && header_find != 3) {
        log("Unexpected CSV header, possible non-integrated tool update!\n=> Expected CSV header: " + expected_header + "\n=> Got CSV header:      " + current_header, level: "error")
      }
      abort
    }

    .hostname = fields[0]
    .address = fields[1]
    .lastseen = fields[2]
    .sourcefile = fields[3]

    .timestamp = .lastseen

    # Add the metadata fields following the parsing.
    .sourcehost = "${SOURCE_HOST:?The source host is required}"
    .host = .sourcehost
    .category = "systeminfo"
    .source = "windows_ual-dnsinfo"
    .sourcetype = "windows_artefact"

    # Delete irrelevant default fields.
    del(.source_type)
    del(.file)
    del(.message)
    del(.__offset)
  '''

[transforms.SumECmd_UAL_DnsInfo_coerce_to_sink]
  type = "remap"
  inputs = ["SumECmd_UAL_DnsInfo_csv_parser"]
  source = '''
    . = map_values(.) -> |value| {
      value_string, convert_err = string(value)
      # Only coerce string (and not already casted types, such as int, timestamps, etc.).
      if convert_err != null {
        value
      # Matches a timestamp in various format ("T" or space separated, with or without post second precision, and with or without a timezone identifier).
      } else if (match(value_string, r'^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[0-1])[T|\s]([01][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9])(\.[0-9]{1,9})?(\s?[\+|\-]([01][0-9]|2[0-4]):?([0-5][0-9]))?$')) {
        tmp_value = parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S%z") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%z") ?? parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S%.f%z") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%.f%z") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%.f %z") ?? parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S") ?? parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S%.f") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%.f") ?? value_string
        if is_string(tmp_value) {
          log("Failed to convert timestamp: " + value_string, level: "warn")
          value
        } else {
          tmp_value
        }
      } else if (tmp_value, err = parse_int(value); err == null) {
        tmp_value
      } else if (tmp_value, err = to_bool(value); err == null) {
        tmp_value
      } else if (tmp_value, err = to_float(value); err == null) {
        tmp_value
      } else {
        value
      }
    }
  '''
