# Vector_Windows_EZTools_JLECmd_Jumplist-AutoDst config.
# Description: Process Windows artefacts parsed with JLECmd (CSV output).
#              Filename should match: "*AutomaticDestinations.csv"
#              JLECmd command: JLECmd.exe -d %sourceDirectory% --csv %destinationDirectory% -q
#              Example command: JLECmd.exe -d "C:\" --csv <YOUR_OUTPUT> -q
#              source = "windows_jumplist-autodst" & sourcetype = "windows_artefact"
# Author(s): Jérôme BREBION, Thomas DIOT (_Qazeer)
# Version: 1.0
# Last modified: 2022-09-28
# Required environment variables:
#   INPUT_FOLDER = "<INPUT_FOLDER>"
#   VECTOR_TEMP_FOLDER = "<VECTOR_TEMP_FOLDER>"
#   SOURCE_HOST = "<SOURCE_HOST>"

# Temporary folder used by Vector.
data_dir = "${VECTOR_TEMP_FOLDER:?A directory for Vector temporary data is required}"

# Set the default timezone to UTC+0 for timestamps that do not include a timezone.
timezone = "Etc/UTC"

[sources.JLECmd_Jumplist-AutoDst_csv_input]
  type = "file"
  include = ["${INPUT_FOLDER:?The input folder containing the JLECmd Jumplist Automatic Destinations files is required.}/*/FileFolderAccess/*AutomaticDestinations.csv"]
  ignore_checkpoints = true
  read_from = "beginning"
  oldest_first = false
  glob_minimum_cooldown_ms = 100000
  fingerprint.strategy = "device_and_inode"
  max_line_bytes = 100_000_000
  offset_key = "__offset"

[transforms.JLECmd_Jumplist-AutoDst_csv_parser]
  type = "remap"
  inputs = ["JLECmd_Jumplist-AutoDst_csv_input"]
  source = '''
    # Expect CSV header:
    # Old: SourceFile,SourceCreated,SourceModified,SourceAccessed,AppId,AppIdDescription,DestListVersion,LastUsedEntryNumber,MRU,EntryNumber,CreationTime,LastModified,Hostname,MacAddress,Path,InteractionCount,PinStatus,FileBirthDroid,FileDroid,VolumeBirthDroid,VolumeDroid,TargetCreated,TargetModified,TargetAccessed,FileSize,RelativePath,WorkingDirectory,FileAttributes,HeaderFlags,DriveType,VolumeSerialNumber,VolumeLabel,LocalPath,CommonPath,TargetIDAbsolutePath,TargetMFTEntryNumber,TargetMFTSequenceNumber,MachineID,MachineMACAddress,TrackerCreatedOn,ExtraBlocksPresent,Arguments,Notes
    # New: SourceFile,SourceCreated,SourceModified,SourceAccessed,AppId,AppIdDescription,HasSps,DestListVersion,LastUsedEntryNumber,MRU,EntryNumber,CreationTime,LastModified,Hostname,MacAddress,Path,InteractionCount,PinStatus,FileBirthDroid,FileDroid,VolumeBirthDroid,VolumeDroid,TargetCreated,TargetModified,TargetAccessed,FileSize,RelativePath,WorkingDirectory,FileAttributes,HeaderFlags,DriveType,VolumeSerialNumber,VolumeLabel,LocalPath,CommonPath,TargetIDAbsolutePath,TargetMFTEntryNumber,TargetMFTSequenceNumber,MachineID,MachineMACAddress,TrackerCreatedOn,ExtraBlocksPresent,Arguments,Notes
    fields, err = parse_csv(.message, delimiter: ",")
    if err != null {
      log("Unable to split CSV: " + err, level: "error")
    }

    if .__offset == 0 {
      expected_header = "SourceFile,SourceCreated,SourceModified,SourceAccessed,AppId,AppIdDescription,HasSps,DestListVersion,LastUsedEntryNumber,MRU,EntryNumber,CreationTime,LastModified,Hostname,MacAddress,Path,InteractionCount,PinStatus,FileBirthDroid,FileDroid,VolumeBirthDroid,VolumeDroid,TargetCreated,TargetModified,TargetAccessed,FileSize,RelativePath,WorkingDirectory,FileAttributes,HeaderFlags,DriveType,VolumeSerialNumber,VolumeLabel,LocalPath,CommonPath,TargetIDAbsolutePath,TargetMFTEntryNumber,TargetMFTSequenceNumber,MachineID,MachineMACAddress,TrackerCreatedOn,ExtraBlocksPresent,Arguments,Notes"
      current_header = strip_whitespace(string!(.message))
      if expected_header != current_header {
        log("Unexpected CSV header, possible non-integrated tool update!\n=> Expected CSV header: " + expected_header + "\n=> Got CSV header:      " + current_header, level: "error")
      }
      abort
    }

    .sourcefile = fields[0]
    .sourcecreated = fields[1]
    .sourcemodified = fields[2]
    .sourceaccessed = fields[3]
    .appid = fields[4]
    .appiddescription = fields[5]
    .hassps = fields[6]
    .destlistversion = fields[7]
    .lastusedentrynumber = fields[8]
    .mru = fields[9]
    .entrynumber = fields[10]
    .creationtime = fields[11]
    if (fields[12] != "1601-01-01 00:00:00") {
      .lastmodified = fields[12]
    }
    .hostname = fields[13]
    .macaddress = fields[14]
    .path = fields[15]
    .interactioncount = fields[16]
    .pinstatus = fields[17]
    .filebirthdroid = fields[18]
    .filedroid = fields[19]
    .volumebirthdroid = fields[20]
    .volumedroid  = fields[21]
    .targetcreated = fields[22]
    .targetmodified = fields[23]
    .targetaccessed = fields[24]
    .filesize = fields[25]
    .relativepath = fields[26]
    .workingdirectory = fields[27]
    .fileattributes = fields[28]
    .headerflags = fields[29]
    .drivetype = fields[30]
    .volumeserialnumber = fields[31]
    .volumelabel = fields[32]
    .localpath = fields[33]
    .commonpath = fields[34]
    .targetidabsolutepath = fields[35]
    .targetmftentrynumber = fields[36]
    .targetmftsequencenumber = fields[37]
    .machineid = fields[38]
    .machinemacaddress = fields[39]
    .trackercreatedon = fields[40]
    .arguments = fields[41]
    .notes = fields[42]

    .timestamp = .lastmodified

    if (match_user, err = parse_regex(fields[0], r'.*(\\|/)(?P<username>.*?)(\\|/)AppData(\\|/).*'); err == null) {
      .user = match_user.username
    } else {
      .user = ""
    }

    # Add the metadata fields following the parsing.
    .sourcehost = "${SOURCE_HOST:?The source host is required}"
    .host = .sourcehost
    .category = "filefolderaccess"
    .source = "windows_jumplist-autodst"
    .sourcetype = "windows_artefact"

    # Delete irrelevant default fields.
    del(.source_type)
    del(.file)
    del(.message)
    del(.__offset)
  '''

[transforms.JLECmd_Jumplist-AutoDst_coerce]
  type = "remap"
  inputs = ["JLECmd_Jumplist-AutoDst_csv_parser"]
  source = '''
    . = map_values(.) -> |value| {
      value_string, convert_err = string(value)
      # Only coerce string (and not already casted types, such as int, timestamps, etc.).
      if convert_err != null {
        value
      # Matches a timestamp in various format ("T" or space separated, with or without post second precision, and with or without a timezone identifier).
      } else if (match(value_string, r'^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[0-1])[T|\s]([01][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9])(\.[0-9]{1,9})?(\s?[\+|\-]([01][0-9]|2[0-4]):?([0-5][0-9]))?$')) {
        tmp_value = parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S%z") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%z") ?? parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S%.f%z") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%.f%z") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%.f %z") ?? parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S") ?? parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S%.f") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%.f") ?? value_string
        if is_string(tmp_value) {
          log("Failed to convert timestamp: " + value_string, level: "warn")
          value
        } else {
          tmp_value
        }
      } else if (tmp_value, err = parse_int(value); err == null) {
        tmp_value
      } else if (tmp_value, err = to_bool(value); err == null) {
        tmp_value
      } else if (tmp_value, err = to_float(value); err == null) {
        tmp_value
      } else {
        value
      }
    }
  '''

[transforms.JLECmd_Jumplist-AutoDst_dedup_LastModified_to_sink]
  type = "remap"
  inputs = ["JLECmd_Jumplist-AutoDst_coerce"]
  source = '''
    if is_nullish(.lastmodified) {
      abort
    }

    .timestamp = .lastmodified
    .operation = "modification"
    .suboperation = "file_modification_lastmodified"
  '''

[transforms.JLECmd_Jumplist-AutoDst_dedup_SourceCreated_to_sink]
  type = "remap"
  inputs = ["JLECmd_Jumplist-AutoDst_coerce"]
  source = '''
    if is_nullish(.sourcecreated) {
      abort
    }

    .timestamp = .sourcecreated
    .operation = "creation"
    .suboperation = "file_creation_sourcecreated"
  '''

[transforms.JLECmd_Jumplist-AutoDst_dedup_SourceModified_to_sink]
  type = "remap"
  inputs = ["JLECmd_Jumplist-AutoDst_coerce"]
  source = '''
    if is_nullish(.sourcemodified) {
      abort
    }

    .timestamp = .sourcemodified
    .operation = "modification"
    .suboperation = "file_modification_sourcemodified"
  '''

[transforms.JLECmd_Jumplist-AutoDst_dedup_SourceAccessed_to_sink]
  type = "remap"
  inputs = ["JLECmd_Jumplist-AutoDst_coerce"]
  source = '''
    if is_nullish(.sourceaccessed) {
      abort
    }

    .timestamp = .sourceaccessed
    .operation = "access"
    .suboperation = "file_access_sourceaccessed"
  '''

[transforms.JLECmd_Jumplist-AutoDst_dedup_CreationTime_to_sink]
  type = "remap"
  inputs = ["JLECmd_Jumplist-AutoDst_coerce"]
  source = '''
    if is_nullish(.creationtime) {
      abort
    }

    .timestamp = .creationtime
    .operation = "creation"
    .suboperation = "file_creation_creationtime"
  '''

[transforms.JLECmd_Jumplist-AutoDst_dedup_TargetCreated_to_sink]
  type = "remap"
  inputs = ["JLECmd_Jumplist-AutoDst_coerce"]
  source = '''
    if is_nullish(.targetcreated) {
      abort
    }

    .timestamp = .targetcreated
    .operation = "creation"
    .suboperation = "file_creation_targetcreated"
  '''

[transforms.JLECmd_Jumplist-AutoDst_dedup_TargetModified_to_sink]
  type = "remap"
  inputs = ["JLECmd_Jumplist-AutoDst_coerce"]
  source = '''
    if is_nullish(.targetmodified) {
      abort
    }

    .timestamp = .targetmodified
    .operation = "modification"
    .suboperation = "file_modification_targetmodified"
  '''

[transforms.JLECmd_Jumplist-AutoDst_dedup_TargetAccessed_to_sink]
  type = "remap"
  inputs = ["JLECmd_Jumplist-AutoDst_coerce"]
  source = '''
    if is_nullish(.targetaccessed) {
      abort
    }

    .timestamp = .targetaccessed
    .operation = "access"
    .suboperation = "file_access_targetaccessed"
  '''

[transforms.JLECmd_Jumplist-AutoDst_dedup_TrackerCreatedOn_to_sink]
  type = "remap"
  inputs = ["JLECmd_Jumplist-AutoDst_coerce"]
  source = '''
    if is_nullish(.trackercreatedon) {
      abort
    }

    .timestamp = .trackercreatedon
    .operation = "creation"
    .suboperation = "file_creation_trackercreatedon"
  '''
