# Vector_Windows_EZTools_SrumECmd_Srum_dump config.
# Description: Process Windows artefacts parsed with SrumECmd (CSV output).
#              Filename should match: "*SrumECmd*.csv"
#              SrumECmd command: SrumECmd.exe -d %sourceDirectory% -k --csv %destinationDirectory%
#              Example command: SrumECmd.exe -d "C:\" -k --csv <YOUR_OUTPUT>
#              source = "windows_srum_appresourceuseinfo|windows_srum_apptimelineprovider|windows_srum_energyusage|windows_srum_networkconnections|windows_srum_networkusages|windows_srum_pushnotifications|windows_srum_unknownd8f" & sourcetype = "windows_artefact"
# Author(s): Jérôme BREBION, Thomas DIOT (_Qazeer)
# Version: 1.0
# Last modified: 2022-09-28
# Required environment variables:
#   INPUT_FOLDER = "<INPUT_FOLDER>"
#   VECTOR_TEMP_FOLDER = "<VECTOR_TEMP_FOLDER>"
#   SOURCE_HOST = "<SOURCE_HOST>"

# Temporary folder used by Vector.
data_dir = "${VECTOR_TEMP_FOLDER:?A directory for Vector temporary data is required}"

# Set the default timezone to UTC+0 for timestamps that do not include a timezone.
timezone = "Etc/UTC"

[sources.SrumECmd_Srum_dump_csv_input]
  type = "file"
  include = ["${INPUT_FOLDER:?The input folder containing the SrumECmd Srum Dump files is required.}/*/SRUM/*SrumECmd*.csv"]
  ignore_checkpoints = true
  read_from = "beginning"
  oldest_first = false
  glob_minimum_cooldown_ms = 100000
  fingerprint.strategy = "device_and_inode"
  max_line_bytes = 100_000_000
  offset_key = "__offset"

[transforms.SrumECmd_Srum_dump_csv_parser]
  type = "remap"
  inputs = ["SrumECmd_Srum_dump_csv_input"]
  source = '''
    # Expect CSV headers:
    # AppResourceUseInfo: Id,Timestamp,ExeInfo,ExeInfoDescription,ExeTimestamp,SidType,Sid,UserName,UserId,AppId,BackgroundBytesRead,BackgroundBytesWritten,BackgroundContextSwitches,BackgroundCycleTime,BackgroundNumberOfFlushes,BackgroundNumReadOperations,BackgroundNumWriteOperations,FaceTime,ForegroundBytesRead,ForegroundBytesWritten,ForegroundContextSwitches,ForegroundCycleTime,ForegroundNumberOfFlushes,ForegroundNumReadOperations,ForegroundNumWriteOperations
    # AppTimelineProvider: Id,Timestamp,ExeInfo,ExeInfoDescription,ExeTimestamp,SidType,Sid,UserName,UserId,AppId,EndTime,DurationMs
    # EnergyUsage: Id,Timestamp,ExeInfo,ExeInfoDescription,ExeTimestamp,SidType,Sid,UserName,UserId,AppId,IsLt,ConfigurationHash,EventTimestamp,StateTransition,ChargeLevel,CycleCount,DesignedCapacity,FullChargedCapacity,ActiveAcTime,ActiveDcTime,ActiveDischargeTime,ActiveEnergy,CsAcTime,CsDcTime,CsDischargeTime,CsEnergy
    # NetworkConnections: Id,Timestamp,ExeInfo,ExeInfoDescription,ExeTimestamp,SidType,Sid,UserName,UserId,AppId,ConnectedTime,ConnectStartTime,InterfaceLuid,InterfaceType,L2ProfileFlags,L2ProfileId,ProfileName
    # NetworkUsages: Id,Timestamp,ExeInfo,ExeInfoDescription,ExeTimestamp,SidType,Sid,UserName,UserId,AppId,BytesReceived,BytesSent,InterfaceLuid,InterfaceType,L2ProfileFlags,L2ProfileId,ProfileName
    # PushNotifications: Id,Timestamp,ExeInfo,ExeInfoDescription,ExeTimestamp,SidType,Sid,UserName,UserId,AppId,NetworkType,NotificationType,PayloadSize
    # Unknown312 (AppTimelineProvider): Id,Timestamp,ExeInfo,ExeInfoDescription,ExeTimestamp,SidType,Sid,UserName,UserId,AppId,EndTime,DurationMs
    # UnknownD8F: Id,Timestamp,UserId,AppId,ExeInfo,ExeInfoDescription,ExeTimestamp,SidType,Sid,UserName,StartTime,EndTime,Flags,Duration

    fields, err = parse_csv(.message, delimiter: ",")
    if err != null {
      log("Unable to split CSV: " + err, level: "error")
    }

    .id = fields[0]
    .timestamp = fields[1]

    if (contains!(.file, "AppResourceUseInfo")) {
      .source = "windows_srum_appresourceuseinfo"

      if .__offset == 0 {
        # Special usecase as the header line may (or may not) start with 'M-oM-;M-?' (UTF-8 with BOM).
        expected_header = "Id,Timestamp,ExeInfo,ExeInfoDescription,ExeTimestamp,SidType,Sid,UserName,UserId,AppId,BackgroundBytesRead,BackgroundBytesWritten,BackgroundContextSwitches,BackgroundCycleTime,BackgroundNumberOfFlushes,BackgroundNumReadOperations,BackgroundNumWriteOperations,FaceTime,ForegroundBytesRead,ForegroundBytesWritten,ForegroundContextSwitches,ForegroundCycleTime,ForegroundNumberOfFlushes,ForegroundNumReadOperations,ForegroundNumWriteOperations"
        current_header = strip_whitespace(to_string!(.message))
        header_find = find(current_header, expected_header)
        if header_find == -1 || (header_find != 0 && header_find != 3) {
          log("Unexpected CSV header for AppResourceUseInfo, possible non-integrated tool update!\n=> Expected CSV header: " + expected_header + "\n=> Got CSV header:      " + current_header, level: "error")
        }
        abort
      }

      .exeinfo = fields[2]
      .exeinfodescription = fields[3]
      .exetimestamp = fields[4]
      .sidtype = fields[5]
      .sid = fields[6]
      .username = fields[7]
      .userid = fields[8]
      .appid = fields[9]
      .backgroundbytesread = fields[10]
      .backgroundbyteswritten = fields[11]
      .backgroundcontextswitches = fields[12]
      .backgroundcycletime = fields[13]
      .backgroundnumberofflushes = fields[14]
      .backgroundnumreadoperations = fields[15]
      .backgroundnumwriteoperations = fields[16]
      .facetime = fields[17]
      .foregroundbytesread = fields[18]
      .foregroundbyteswritten = fields[19]
      .foregroundcontextswitches = fields[20]
      .foregroundcycletime = fields[21]
      .foregroundnumberofflushes = fields[22]
      .foregroundnumreadoperations = fields[23]
      .foregroundnumwriteoperations = fields[24]

      .exe = .exeinfo

    } else if (contains!(.file, "AppTimelineProvider") || contains!(.file, "Unknown312")) {
      .source = "windows_srum_apptimelineprovider"

      if .__offset == 0 {
        # Special usecase as the header line may (or may not) start with 'M-oM-;M-?' (UTF-8 with BOM).
        expected_header = "Id,Timestamp,ExeInfo,ExeInfoDescription,ExeTimestamp,SidType,Sid,UserName,UserId,AppId,EndTime,DurationMs"
        current_header = strip_whitespace(to_string!(.message))
        header_find = find(current_header, expected_header)
        if header_find == -1 || (header_find != 0 && header_find != 3) {
          log("Unexpected CSV header for Unknown312, possible non-integrated tool update!\n=> Expected CSV header: " + expected_header + "\n=> Got CSV header:      " + current_header, level: "error")
        }
        abort
      }

      .exeinfo = fields[2]
      .exeinfodescription = fields[3]
      .exetimestamp = fields[4]
      .sidtype = fields[5]
      .sid = fields[6]
      .username = fields[7]
      .userid = fields[8]
      .appid = fields[9]
      .endtime = fields[10]
      .durationms = fields[11]

      .exe = .exeinfo

    } else if (contains!(.file, "EnergyUsage")) {
      .source = "windows_srum_energyusage"

      if .__offset == 0 {
        # Special usecase as the header line may (or may not) start with 'M-oM-;M-?' (UTF-8 with BOM).
        expected_header = "Id,Timestamp,ExeInfo,ExeInfoDescription,ExeTimestamp,SidType,Sid,UserName,UserId,AppId,IsLt,ConfigurationHash,EventTimestamp,StateTransition,ChargeLevel,CycleCount,DesignedCapacity,FullChargedCapacity,ActiveAcTime,ActiveDcTime,ActiveDischargeTime,ActiveEnergy,CsAcTime,CsDcTime,CsDischargeTime,CsEnergy"
        current_header = strip_whitespace(to_string!(.message))
        header_find = find(current_header, expected_header)
        if header_find == -1 || (header_find != 0 && header_find != 3) {
          log("Unexpected CSV header for EnergyUsage, possible non-integrated tool update!\n=> Expected CSV header: " + expected_header + "\n=> Got CSV header:      " + current_header, level: "error")
        }
        abort
      }

      .exeinfo = fields[2]
      .exeinfodescription = fields[3]
      .exetimestamp = fields[4]
      .sidtype = fields[5]
      .sid = fields[6]
      .username = fields[7]
      .userid = fields[8]
      .appid = fields[9]
      .islt = fields[10]
      .configurationhash = fields[11]
      .eventtimestamp = fields[12]
      .statetransition = fields[13]
      .chargelevel = fields[14]
      .cyclecount = fields[15]
      .designedcapacity = fields[16]
      .fullchargedcapacity = fields[17]
      .activeactime = fields[18]
      .activedctime = fields[19]
      .activedischargetime = fields[20]
      .activeenergy = fields[21]
      .csactime = fields[22]
      .csdctime = fields[23]
      .csdischargetime = fields[24]
      .csenergy = fields[25]

      .exe = .exeinfo

    } else if (contains!(.file, "NetworkConnections")) {
      .source = "windows_srum_networkconnections"

      if .__offset == 0 {
        # Special usecase as the header line may (or may not) start with 'M-oM-;M-?' (UTF-8 with BOM).
        expected_header = "Id,Timestamp,ExeInfo,ExeInfoDescription,ExeTimestamp,SidType,Sid,UserName,UserId,AppId,ConnectedTime,ConnectStartTime,InterfaceLuid,InterfaceType,L2ProfileFlags,L2ProfileId,ProfileName"
        current_header = strip_whitespace(to_string!(.message))
        header_find = find(current_header, expected_header)
        if header_find == -1 || (header_find != 0 && header_find != 3) {
          log("Unexpected CSV header for NetworkConnections, possible non-integrated tool update!\n=> Expected CSV header: " + expected_header + "\n=> Got CSV header:      " + current_header, level: "error")
        }
        abort
      }

      .exeinfo = fields[2]
      .exeinfodescription = fields[3]
      .exetimestamp = fields[4]
      .sidtype = fields[5]
      .sid = fields[6]
      .username = fields[7]
      .userid = fields[8]
      .appid = fields[9]
      .connectedtime = fields[10]
      .connectstarttime = fields[11]
      .interfaceluid = fields[12]
      .interfacetype = fields[13]
      .l2profileflags = fields[14]
      .l2profileid = fields[15]
      .profilename = fields[16]

      .exe = .exeinfo

    } else if (contains!(.file, "NetworkUsages")) {
      .source = "windows_srum_networkusages"

      if .__offset == 0 {
        # Special usecase as the header line may (or may not) start with 'M-oM-;M-?' (UTF-8 with BOM).
        expected_header = "Id,Timestamp,ExeInfo,ExeInfoDescription,ExeTimestamp,SidType,Sid,UserName,UserId,AppId,BytesReceived,BytesSent,InterfaceLuid,InterfaceType,L2ProfileFlags,L2ProfileId,ProfileName"
        current_header = strip_whitespace(to_string!(.message))
        header_find = find(current_header, expected_header)
        if header_find == -1 || (header_find != 0 && header_find != 3) {
          log("Unexpected CSV header for NetworkUsages, possible non-integrated tool update!\n=> Expected CSV header: " + expected_header + "\n=> Got CSV header:      " + current_header, level: "error")
        }
        abort
      }

      .exeinfo = fields[2]
      .exeinfodescription = fields[3]
      .exetimestamp = fields[4]
      .sidtype = fields[5]
      .sid = fields[6]
      .username = fields[7]
      .userid = fields[8]
      .appid = fields[9]
      .bytesreceived = fields[10]
      .bytessent = fields[11]
      .interfaceluid = fields[12]
      .interfacetype = fields[13]
      .l2profileflags = fields[14]
      .l2profileid = fields[15]
      .profilename = fields[16]

      .exe = .exeinfo

    } else if (contains!(.file, "PushNotifications")) {
      .source = "windows_srum_pushnotifications"

      if .__offset == 0 {
        # Special usecase as the header line may (or may not) start with 'M-oM-;M-?' (UTF-8 with BOM).
        expected_header = "Id,Timestamp,ExeInfo,ExeInfoDescription,ExeTimestamp,SidType,Sid,UserName,UserId,AppId,NetworkType,NotificationType,PayloadSize"
        current_header = strip_whitespace(to_string!(.message))
        header_find = find(current_header, expected_header)
        if header_find == -1 || (header_find != 0 && header_find != 3) {
          log("Unexpected CSV header for PushNotifications, possible non-integrated tool update!\n=> Expected CSV header: " + expected_header + "\n=> Got CSV header:      " + current_header, level: "error")
        }
        abort
      }

      .exeinfo = fields[2]
      .exeinfodescription = fields[3]
      .exetimestamp = fields[4]
      .sidtype = fields[5]
      .sid = fields[6]
      .username = fields[7]
      .userid = fields[8]
      .appid = fields[9]
      .networktype = fields[10]
      .notificationtype = fields[11]
      .payloadsize = fields[12]

      .exe = .exeinfo

    } else if (contains!(.file, "UnknownD8F")) {
      .source = "windows_srum_unknownd8f"

      if .__offset == 0 {
        # Special usecase as the header line may (or may not) start with 'M-oM-;M-?' (UTF-8 with BOM).
        expected_header = "Id,Timestamp,UserId,AppId,ExeInfo,ExeInfoDescription,ExeTimestamp,SidType,Sid,UserName,StartTime,EndTime,Flags,Duration"
        current_header = strip_whitespace(to_string!(.message))
        header_find = find(current_header, expected_header)
        if header_find == -1 || (header_find != 0 && header_find != 3) {
          log("Unexpected CSV header for UnknownD8F, possible non-integrated tool update!\n=> Expected CSV header: " + expected_header + "\n=> Got CSV header:      " + current_header, level: "error")
        }
        abort
      }

      .userid = fields[2]
      .appid = fields[3]
      .exeinfo = fields[4]
      .exeinfodescription = fields[5]
      .exetimestamp = fields[6]
      .sidtype = fields[7]
      .sid = fields[8]
      .username = fields[9]
      .starttime = fields[10]
      .endtime = fields[11]
      .flags = fields[12]
      .duration = fields[13]

    } else {
      log("Unsupported SrumECmd (SRUM) output file: " + string!(.file), level: "warn")
      abort
    }

    # Add the metadata fields following the parsing.
    .sourcehost = "${SOURCE_HOST:?The source host is required}"
    .host = .sourcehost
    .category = "execution"
    .sourcetype = "windows_artefact"

    # Delete irrelevant default fields.
    del(.source_type)
    del(.file)
    del(.message)
    del(.__offset)
  '''

[transforms.SrumECmd_Srum_dump_coerce]
  type = "remap"
  inputs = ["SrumECmd_Srum_dump_csv_parser"]
  source = '''
    . = map_values(.) -> |value| {
      value_string, convert_err = string(value)
      # Only coerce string (and not already casted types, such as int, timestamps, etc.).
      if convert_err != null {
        value
      # Matches a timestamp in various format ("T" or space separated, with or without post second precision, and with or without a timezone identifier).
      } else if (match(value_string, r'^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[0-1])[T|\s]([01][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9])(\.[0-9]{1,9})?(\s?[\+|\-]([01][0-9]|2[0-4]):?([0-5][0-9]))?$')) {
        tmp_value = parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S%z") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%z") ?? parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S%.f%z") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%.f%z") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%.f %z") ?? parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S") ?? parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S%.f") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%.f") ?? value_string
        if is_string(tmp_value) {
          log("Failed to convert timestamp: " + value_string, level: "warn")
          value
        } else {
          tmp_value
        }
      } else if (tmp_value, err = parse_int(value); err == null) {
        tmp_value
      } else if (tmp_value, err = to_bool(value); err == null) {
        tmp_value
      } else if (tmp_value, err = to_float(value); err == null) {
        tmp_value
      } else {
        value
      }
    }
  '''

[transforms.SrumECmd_Srum_dump_dedup_Timestamp_to_sink]
  type = "remap"
  inputs = ["SrumECmd_Srum_dump_coerce"]
  source = '''
    if is_nullish(.timestamp) {
      abort
    }

    .operation = "modification"
    .suboperation = "modification_timestamp"
  '''

[transforms.SrumECmd_Srum_dump_dedup_EventTimestamp_to_sink]
  type = "remap"
  inputs = ["SrumECmd_Srum_dump_coerce"]
  source = '''
    if is_nullish(.eventtimestamp) {
      abort
    }

    .timestamp = .eventtimestamp
    .operation = "modification"
    .suboperation = "modification_eventtimestamp"
  '''

  [transforms.SrumECmd_Srum_dump_dedup_ExeTimestamp_to_sink]
    type = "remap"
    inputs = ["SrumECmd_Srum_dump_coerce"]
    source = '''
      # exetimestamp is sometimes malformated.
      if is_nullish(.exetimestamp) || !is_timestamp(.exetimestamp) {
        abort
      }

      .timestamp = .exetimestamp
      .category = "execution"
      .suboperation = "execution_exetimestamp"
  '''

[transforms.SrumECmd_Srum_dump_dedup_ConnectStartTime_to_sink]
  type = "remap"
  inputs = ["SrumECmd_Srum_dump_coerce"]
  source = '''
    if is_nullish(.connectstarttime) {
      abort
    }

    .timestamp = .connectstarttime
    .operation = "connection"
    .suboperation = "connection_connectstarttime"
  '''

[transforms.SrumECmd_Srum_dump_dedup_StartTime_to_sink]
  type = "remap"
  inputs = ["SrumECmd_Srum_dump_coerce"]
  source = '''
    if is_nullish(.starttime) {
      abort
    }

    .timestamp = .starttime
    .category = "execution"
    .suboperation = "execution_starttime"
  '''

[transforms.SrumECmd_Srum_dump_dedup_EndTime_to_sink]
  type = "remap"
  inputs = ["SrumECmd_Srum_dump_coerce"]
  source = '''
    if is_nullish(.endtime) {
      abort
    }

    .timestamp = .endtime
    .category = "execution"
    .suboperation = "execution_endtime"
  '''
