# Vector_Windows_EZTools_WxTCmd_Activitydb config.
# Description: Process Windows artefacts parsed with WxTCmd (CSV output).
#              Filename should match: "*_Activity.csv"
#              WxTCmd command: WxTCmd.exe -f %sourceFile% --csv %destinationDirectory%
#              Example command: WxTCmd.exe -f "C:\Users\<USER>\AppData\Local\ConnectedDevicesPlatform\<FOLDER>\ActivitiesCache.db" --csv <YOUR_OUTPUT>
#              source = "windows_activitydb" & sourcetype = "windows_artefact"
# Author(s): Jérôme BREBION, Thomas DIOT (_Qazeer)
# Version: 1.0
# Last modified: 2022-09-28
# Required environment variables:
#   INPUT_FOLDER = "<INPUT_FOLDER>"
#   VECTOR_TEMP_FOLDER = "<VECTOR_TEMP_FOLDER>"
#   SOURCE_HOST = "<SOURCE_HOST>"

# Temporary folder used by Vector.
data_dir = "${VECTOR_TEMP_FOLDER:?A directory for Vector temporary data is required}"

# Set the default timezone to UTC+0 for timestamps that do not include a timezone.
timezone = "Etc/UTC"

[sources.WxTCmd_Activitydb_csv_input]
  type = "file"
  include = ["${INPUT_FOLDER:?The input folder containing the WxTCmd Activitydb files is required.}/*/FileFolderAccess/*_Activity.csv"]
  ignore_checkpoints = true
  read_from = "beginning"
  oldest_first = false
  glob_minimum_cooldown_ms = 100000
  fingerprint.strategy = "device_and_inode"
  max_line_bytes = 100_000_000
  offset_key = "__offset"

[transforms.WxTCmd_Activitydb_csv_parser]
  type = "remap"
  inputs = ["WxTCmd_Activitydb_csv_input"]
  source = '''
    # Expect CSV header:
    # Old: Id,Executable,DisplayText,ContentInfo,StartTime,EndTime,LastModifiedTime,ExpirationTime,CreatedInCloud,LastModifiedOnClient,OriginalLastModifiedOnClient,ActivityType,IsLocalOnly,ETag,PackageIdHash,PlatformDeviceId,Duration
    # New: Id,ActivityTypeOrg,ActivityType,Executable,DisplayText,ContentInfo,Payload,ClipboardPayload,StartTime,EndTime,Duration,LastModifiedTime,LastModifiedOnClient,OriginalLastModifiedOnClient,ExpirationTime,CreatedInCloud,IsLocalOnly,ETag,PackageIdHash,PlatformDeviceId,DevicePlatform,TimeZone
    if .__offset == 0 {
      # Special usecase as the header line may (or may not) start with 'M-oM-;M-?' (UTF-8 with BOM).
      expected_header = "Id,ActivityTypeOrg,ActivityType,Executable,DisplayText,ContentInfo,Payload,ClipboardPayload,StartTime,EndTime,Duration,LastModifiedTime,LastModifiedOnClient,OriginalLastModifiedOnClient,ExpirationTime,CreatedInCloud,IsLocalOnly,ETag,PackageIdHash,PlatformDeviceId,DevicePlatform,TimeZone"
      current_header = strip_whitespace(to_string!(.message))
      header_find = find(current_header, expected_header)
      if header_find == -1 || (header_find != 0 && header_find != 3) {
        log("Unexpected CSV header, possible non-integrated tool update!\n=> Expected CSV header: " + expected_header + "\n=> Got CSV header:      " + current_header, level: "error")
      }
      abort
    }

    fields, err = parse_csv(.message, delimiter: ",")
    if err != null {
      log("Unable to split CSV: " + err, level: "error")
    }

    .id = fields[0]
    .activitytypeorg  = fields[1]
    .activitytype = fields[2]
    .executable = fields[3]
    .displaytext = fields[4]
    .contentinfo = fields[5]
    .payload = fields[6]
    .clipboardpayload = fields[7]
    .starttime = fields[8]
    .endtime = fields[9]
    .duration = fields[10]
    .lastmodifiedtime = fields[11]
    .lastmodifiedonclient = fields[12]
    .originallastmodifiedonclient = fields[13]
    .expirationtime = fields[14]
    .createdincloud = fields[15]
    .islocalonly = fields[16]
    .etag = fields[17]
    .packageidhash = fields[18]
    .platformdeviceid = fields[19]
    .deviceplatform = fields[20]
    .timezone = fields[21]

    .exe = .executable

    # Add the metadata fields following the parsing.
    .sourcehost = "${SOURCE_HOST:?The source host is required}"
    .host = .sourcehost
    .category = "execution"
    .source = "windows_activitydb"
    .sourcetype = "windows_artefact"

    # Delete irrelevant default fields.
    del(.source_type)
    del(.file)
    del(.message)
    del(.__offset)
  '''

[transforms.WxTCmd_Activitydb_coerce]
  type = "remap"
  inputs = ["WxTCmd_Activitydb_csv_parser"]
  source = '''
    . = map_values(.) -> |value| {
      value_string, convert_err = string(value)
      # Only coerce string (and not already casted types, such as int, timestamps, etc.).
      if convert_err != null {
        value
      # Matches a timestamp in various format ("T" or space separated, with or without post second precision, and with or without a timezone identifier).
      } else if (match(value_string, r'^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[0-1])[T|\s]([01][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9])(\.[0-9]{1,9})?(\s?[\+|\-]([01][0-9]|2[0-4]):?([0-5][0-9]))?$')) {
        tmp_value = parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S%z") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%z") ?? parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S%.f%z") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%.f%z") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%.f %z") ?? parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S") ?? parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S%.f") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%.f") ?? value_string
        if is_string(tmp_value) {
          log("Failed to convert timestamp: " + value_string, level: "warn")
          value
        } else {
          tmp_value
        }
      } else if (tmp_value, err = parse_int(value); err == null) {
        tmp_value
      } else if (tmp_value, err = to_bool(value); err == null) {
        tmp_value
      } else if (tmp_value, err = to_float(value); err == null) {
        tmp_value
      } else {
        value
      }
    }
  '''

[transforms.WxTCmd_Activitydb_dedup_StartTime_to_sink]
  type = "remap"
  inputs = ["WxTCmd_Activitydb_coerce"]
  source = '''
    if is_nullish(.starttime) {
      abort
    }

    .timestamp = .starttime
    .category = "execution"
    .suboperation = "execution_starttime"
  '''

[transforms.WxTCmd_Activitydb_dedup_EndTime_to_sink]
  type = "remap"
  inputs = ["WxTCmd_Activitydb_coerce"]
  source = '''
    if is_nullish(.endtime) {
      abort
    }

    .timestamp = .endtime
    .category = "execution"
    .suboperation = "execution_endtime"
  '''

[transforms.WxTCmd_Activitydb_dedup_LastModifiedTime_to_sink]
  type = "remap"
  inputs = ["WxTCmd_Activitydb_coerce"]
  source = '''
    if is_nullish(.lastmodifiedtime) {
      abort
    }

    .timestamp = .lastmodifiedtime
    .operation = "modification"
    .suboperation = "database_modification_lastmodifiedtime"
  '''

[transforms.WxTCmd_Activitydb_dedup_ExpirationTime_to_sink]
  type = "remap"
  inputs = ["WxTCmd_Activitydb_coerce"]
  source = '''
    if is_nullish(.expirationtime) {
      abort
    }

    .timestamp = .expirationtime
    .operation = "expiration"
    .suboperation = "expirationtime"
  '''

[transforms.WxTCmd_Activitydb_dedup_LastModifiedOnClient_to_sink]
  type = "remap"
  inputs = ["WxTCmd_Activitydb_coerce"]
  source = '''
    if is_nullish(.lastmodifiedonclient) {
      abort
    }

    .timestamp = .lastmodifiedonclient
    .operation = "modification"
    .suboperation = "database_modification_lastmodifiedonclient"
  '''

[transforms.WxTCmd_Activitydb_dedup_OriginalLastModifiedOnClient_to_sink]
  type = "remap"
  inputs = ["WxTCmd_Activitydb_coerce"]
  source = '''
    if is_nullish(.originallastmodifiedonclient) {
      abort
    }

    .timestamp = .originallastmodifiedonclient
    .operation = "modification"
    .suboperation = "database_modification_originallastmodifiedonclient"
  '''
