# Vector_Windows_EZTools_MFTECmd_MFT config.
# Description: Process Windows artefacts parsed with MFTECmd (CSV output).
#              Filename should match: "*MFT_Output.csv"
#              MFTECmd command: MFTECmd.exe -f %sourceFile% --csv %destinationDirectory%
#              source = "windows_mft" & sourcetype = "windows_artefact"
# Author(s): Jérôme BREBION, Thomas DIOT (_Qazeer)
# Version: 1.0
# Last modified: 2022-09-28
# Required environment variables:
#   INPUT_FOLDER = "<INPUT_FOLDER>"
#   VECTOR_TEMP_FOLDER = "<VECTOR_TEMP_FOLDER>"
#   SOURCE_HOST = "<SOURCE_HOST>"

# Temporary folder used by Vector.
data_dir = "${VECTOR_TEMP_FOLDER:?A directory for Vector temporary data is required}"

# Set the default timezone to UTC+0 for timestamps that do not include a timezone.
timezone = "Etc/UTC"

[sources.MFTECmd_MFT_csv_input]
  type = "file"
  include = ["${INPUT_FOLDER:?The input folder containing the MFTECmd MFT files is required.}/*/FileSystem/*MFT_Output.csv"]
  ignore_checkpoints = true
  read_from = "beginning"
  oldest_first = false
  glob_minimum_cooldown_ms = 100000
  fingerprint.strategy = "device_and_inode"
  max_line_bytes = 100_000_000
  offset_key = "__offset"

[sources.MFTECmd_MFT_json_input]
  type = "file"
  include = ["${INPUT_FOLDER:?The input folder containing the MFTECmd MFT files is required.}/**/*MFT_Output.json"]
  ignore_checkpoints = true
  read_from = "beginning"
  oldest_first = false
  glob_minimum_cooldown_ms = 100000
  fingerprint.strategy = "device_and_inode"
  max_line_bytes = 100_000_000

[transforms.MFTECmd_MFT_json_parser]
  type = "remap"
  inputs = ["MFTECmd_MFT_json_input"]
  source = '''
    splitted, err = split(.message, "\n")
	  if err != null {
	    log("Unable to split message on newlines: " + err, level: "error")
	  }

    . = map_values(splitted, true) -> |value| {
      parsed_value, err = parse_json(value)
      parsed_value.file = .file

      if err != null {
        log("Unable to parse JSON: " + err, level: "error")
        null
      } else {
        parsed_value
      }
    }

    . = map_keys(object!(.[0])) -> |key| { downcase(key) }

    .created0x10 = .created0x10
    .created0x30 = .created0x30
    .lastmodified0x10 = .lastmodified0x10
    .lastmodified0x30 = .lastmodified0x30
    .lastrecordchange0x10 = .lastrecordchange0x10
    .lastrecordchange0x30 = .lastrecordchange0x30
    .lastaccess0x10 = .lastaccess0x10
    .lastaccess0x30 = .lastaccess0x30

    # Add the metadata fields following the parsing.
    .sourcehost = "${SOURCE_HOST:?The source host is required}"
    .host = .sourcehost
    .category = "filesystem"
    .source = "windows_mft"
    .sourcetype = "windows_artefact"

    # Delete irrelevant default fields.
    del(.file)
    del(.message)
    del(.__offset)
  '''

[transforms.MFTECmd_MFT_csv_parser]
  type = "remap"
  inputs = ["MFTECmd_MFT_csv_input"]
  source = '''
    # Expect CSV header:
    # EntryNumber,SequenceNumber,InUse,ParentEntryNumber,ParentSequenceNumber,ParentPath,FileName,Extension,FileSize,ReferenceCount,ReparseTarget,IsDirectory,HasAds,IsAds,SI<FN,uSecZeros,Copied,SiFlags,NameType,Created0x10,Created0x30,LastModified0x10,LastModified0x30,LastRecordChange0x10,LastRecordChange0x30,LastAccess0x10,LastAccess0x30,UpdateSequenceNumber,LogfileSequenceNumber,SecurityId,ObjectIdFileDroid,LoggedUtilStream,ZoneIdContents
    fields, err = parse_csv(.message, delimiter: ",")
    if err != null {
      log("Unable to split CSV: " + err, level: "error")
    }

    if .__offset == 0 {
      # Special usecase as the header line may (or may not) start with 'M-oM-;M-?' (UTF-8 with BOM).
      expected_header = "EntryNumber,SequenceNumber,InUse,ParentEntryNumber,ParentSequenceNumber,ParentPath,FileName,Extension,FileSize,ReferenceCount,ReparseTarget,IsDirectory,HasAds,IsAds,SI<FN,uSecZeros,Copied,SiFlags,NameType,Created0x10,Created0x30,LastModified0x10,LastModified0x30,LastRecordChange0x10,LastRecordChange0x30,LastAccess0x10,LastAccess0x30,UpdateSequenceNumber,LogfileSequenceNumber,SecurityId,ObjectIdFileDroid,LoggedUtilStream,ZoneIdContents"
      current_header = strip_whitespace(to_string!(.message))
      header_find = find(current_header, expected_header)
      if header_find == -1 || (header_find != 0 && header_find != 3) {
        log("Unexpected CSV header, possible non-integrated tool update!\n=> Expected CSV header: " + expected_header + "\n=> Got CSV header:      " + current_header, level: "error")
      }
      abort
    }

    .entrynumber = fields[0]
    .inuse = fields[2]
    .parentpath = fields[5]
    .filename = fields[6]
    .extension = fields[7]
    .filesize = fields[8]
    .referencecount = fields[9]
    .reparsetarget = fields[10]
    .hasads = fields[12]
    .isads = fields[13]
    .siltfn = fields[14]
    .useczeros = fields[15]
    .copied = fields[16]
    .siflags = fields[17]
    .nametype = fields[18]
    .created0x10 = fields[19]
    .created0x30 = fields[20]
    .lastmodified0x10 = fields[21]
    .lastmodified0x30 = fields[22]
    .lastrecordchange0x10 = fields[23]
    .lastrecordchange0x30 = fields[24]
    .lastaccess0x10 = fields[25]
    .lastaccess0x30 = fields[26]
    .updatesequencenumber = fields[27]
    .logfilesequencenumber = fields[28]
    .securityid = fields[29]

    .timestamp = .lastmodified0x10

    # Add the metadata fields following the parsing.
    .sourcehost = "${SOURCE_HOST:?The source host is required}"
    .host = .sourcehost
    .category = "filesystem"
    .source = "windows_mft"
    .sourcetype = "windows_artefact"

    # Delete irrelevant default fields.
    del(.source_type)
    del(.file)
    del(.message)
    del(.__offset)
  '''

[transforms.MFTECmd_MFT_coerce]
  type = "remap"
  inputs = [
    "MFTECmd_MFT_csv_parser",
    "MFTECmd_MFT_json_parser"
  ]
  source = '''
    . = map_values(.) -> |value| {
      value_string, convert_err = string(value)
      # Only coerce string (and not already casted types, such as int, timestamps, etc.).
      if convert_err != null {
        value
      # Matches a timestamp in various format ("T" or space separated, with or without post second precision, and with or without a timezone identifier).
      } else if (match(value_string, r'^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[0-1])[T|\s]([01][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9])(\.[0-9]{1,9})?(\s?[\+|\-]([01][0-9]|2[0-4]):?([0-5][0-9]))?$')) {
        tmp_value = parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S%z") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%z") ?? parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S%.f%z") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%.f%z") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%.f %z") ?? parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S") ?? parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S%.f") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%.f") ?? value_string
        if is_string(tmp_value) {
          log("Failed to convert timestamp: " + value_string, level: "warn")
          value
        } else {
          tmp_value
        }
      } else if (tmp_value, err = parse_int(value); err == null) {
        tmp_value
      } else if (tmp_value, err = to_bool(value); err == null) {
        tmp_value
      } else if (tmp_value, err = to_float(value); err == null) {
        tmp_value
      } else {
        value
      }
    }
  '''

[transforms.MFTECmd_MFT_dedup_LastModified0x10_to_sink]
  type = "remap"
  inputs = ["MFTECmd_MFT_coerce"]
  source = '''
    if is_nullish(.lastmodified0x10) {
      abort
    }

    .timestamp = .lastmodified0x10
    .operation = "modification"
    .suboperation = "file_modification_stdinfo"
  '''

[transforms.MFTECmd_MFT_dedup_Created0x10_to_sink]
  type = "remap"
  inputs = ["MFTECmd_MFT_coerce"]
  source = '''
    if is_nullish(.created0x10) {
      abort
    }

    .timestamp = .created0x10
    .operation = "creation"
    .suboperation = "file_creation_stdinfo"
  '''

[transforms.MFTECmd_MFT_dedup_LastRecordChange0x10_to_sink]
  type = "remap"
  inputs = ["MFTECmd_MFT_coerce"]
  source = '''
    if is_nullish(.lastrecordchange0x10) {
      abort
    }

    .timestamp = .lastrecordchange0x10
    .operation = "modification"
    .suboperation = "file_modification_stdinfo"
  '''

[transforms.MFTECmd_MFT_dedup_LastAccess0x10_to_sink]
  type = "remap"
  inputs = ["MFTECmd_MFT_coerce"]
  source = '''
    if is_nullish(.lastaccess0x10) {
      abort
    }

    .timestamp = .lastaccess0x10
    .operation = "access"
    .suboperation = "file_access_stdinfo"
  '''
