# Vector_Windows_EZTools_RECmd_LocalAccounts config.
# Description: Process Windows artefacts parsed with RECmd (CSV output).
#              Filename should match: "*_UserAccounts_*.csv"
#              Hive type: SAM
#              Registry key path: SAM\Domains\Account\Users
#              RECmd command: RECmd\RECmd.exe -d %sourceDirectory% --bn RECmd\RECmd_Batch_MC.reb --nl --csv %destinationDirectory% -q
#              Example command: RECmd\RECmd.exe -d "C:\" --bn RECmd\RECmd_Batch_MC.reb --nl --csv <YOUR_OUTPUT> -q
#              source = "windows_registry_localaccounts" & sourcetype = "windows_artefact"
# Author(s): Jérôme BREBION, Thomas DIOT (_Qazeer)
# Version: 1.0
# Last modified: 2022-09-28
# Required environment variables:
#   INPUT_FOLDER = "<INPUT_FOLDER>"
#   VECTOR_TEMP_FOLDER = "<VECTOR_TEMP_FOLDER>"
#   SOURCE_HOST = "<SOURCE_HOST>"

# Temporary folder used by Vector.
data_dir = "${VECTOR_TEMP_FOLDER:?A directory for Vector temporary data is required}"

# Set the default timezone to UTC+0 for timestamps that do not include a timezone.
timezone = "Etc/UTC"

[sources.RECmd_LocalAccounts_csv_input]
  type = "file"
  include = ["${INPUT_FOLDER:?The input folder containing the RECmd Registry Local Accounts files is required.}/*/Registry/*/*_UserAccounts_*.csv"]
  ignore_checkpoints = true
  read_from = "beginning"
  oldest_first = false
  glob_minimum_cooldown_ms = 100000
  fingerprint.strategy = "device_and_inode"
  max_line_bytes = 100_000_000
  offset_key = "__offset"

[transforms.RECmd_LocalAccounts_csv_parser]
  type = "remap"
  inputs = ["RECmd_LocalAccounts_csv_input"]
  source = '''
    # Expect CSV header:
    # BatchKeyPath,BatchValueName,UserId,InvalidLoginCount,TotalLoginCount,CreatedOn,LastLoginTime,LastPasswordChange,LastIncorrectPassword,ExpiresOn,UserName,FullName,PasswordHint,Groups,Comment,UserComment,HomeDirectory,AccountDisabled,HomeDirectoryRequired,PasswordNotRequired,TempDuplicateAccount,NormalUserAccount,MnsLogonAccount,InterdomainTrustAccount,WorkstationTrustAccount,ServerTrustAccount,PasswordDoesNotExpire,AutoLocked
    # ValidUserId,BatchKeyPath,BatchValueName,UserId,InvalidLoginCount,TotalLoginCount,CreatedOn,LastLoginTime,LastPasswordChange,LastIncorrectPassword,ExpiresOn,UserName,FullName,PasswordHint,Groups,Comment,UserComment,HomeDirectory,InternetUserName,ResetData,AccountDisabled,HomeDirectoryRequired,PasswordNotRequired,TempDuplicateAccount,NormalUserAccount,MnsLogonAccount,InterdomainTrustAccount,WorkstationTrustAccount,ServerTrustAccount,PasswordDoesNotExpire,AutoLocked
    fields, err = parse_csv(.message, delimiter: ",")
    if err != null {
      log("Unable to split CSV: " + err, level: "error")
    }

    if .__offset == 0 {
      # Special usecase as the header line may (or may not) start with 'M-oM-;M-?' (UTF-8 with BOM).
      expected_header = "ValidUserId,BatchKeyPath,BatchValueName,UserId,InvalidLoginCount,TotalLoginCount,CreatedOn,LastLoginTime,LastPasswordChange,LastIncorrectPassword,ExpiresOn,UserName,FullName,PasswordHint,Groups,Comment,UserComment,HomeDirectory,InternetUserName,ResetData,AccountDisabled,HomeDirectoryRequired,PasswordNotRequired,TempDuplicateAccount,NormalUserAccount,MnsLogonAccount,InterdomainTrustAccount,WorkstationTrustAccount,ServerTrustAccount,PasswordDoesNotExpire,AutoLocked"
      current_header = strip_whitespace(to_string!(.message))
      header_find = find(current_header, expected_header)
      if header_find == -1 || (header_find != 0 && header_find != 3) {
        log("Unexpected CSV header, possible non-integrated tool update!\n=> Expected CSV header: " + expected_header + "\n=> Got CSV header:      " + current_header, level: "error")
      }
      abort
    }

    .validuserid = fields[0]
    .batchkeypath = fields[1]
    .batchvaluename = fields[2]
    .userid = fields[3]
    .invalidlogincount = fields[4]
    .totallogincount = fields[5]
    .createdon = fields[6]
    .lastlogintime = fields[7]
    .lastpasswordchange = fields[8]
    .lastincorrectpassword = fields[9]
    .expireson = fields[10]
    .username = fields[11]
    .fullname = fields[12]
    .passwordhint = fields[13]
    .groups = fields[14]
    .comment = fields[15]
    .usercomment = fields[16]
    .homedirectory = fields[17]
    .internetusername = fields[18]
    .resetdata = fields[19]
    .accountdisabled = fields[20]
    .homedirectoryrequired = fields[21]
    .passwordnotrequired = fields[22]
    .tempduplicateaccount = fields[23]
    .normaluseraccount = fields[24]
    .mnslogonaccount = fields[25]
    .interdomaintrustaccount = fields[26]
    .workstationtrustaccount = fields[27]
    .servertrustaccount = fields[28]
    .passworddoesnotexpire = fields[29]
    .autolocked = fields[30]

    .timestamp = .createdon

    # Add the metadata fields following the parsing.
    .sourcehost = "${SOURCE_HOST:?The source host is required}"
    .host = .sourcehost
    .category = "systeminfo"
    .source = "windows_registry_localaccounts"
    .sourcetype = "windows_artefact"

    # Delete irrelevant default fields.
    del(.source_type)
    del(.file)
    del(.message)
    del(.__offset)
  '''

[transforms.RECmd_LocalAccounts_coerce]
  type = "remap"
  inputs = ["RECmd_LocalAccounts_csv_parser"]
  source = '''
    . = map_values(.) -> |value| {
      value_string, convert_err = string(value)
      # Only coerce string (and not already casted types, such as int, timestamps, etc.).
      if convert_err != null {
        value
      # Matches a timestamp in various format ("T" or space separated, with or without post second precision, and with or without a timezone identifier).
      } else if (match(value_string, r'^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[0-1])[T|\s]([01][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9])(\.[0-9]{1,9})?(\s?[\+|\-]([01][0-9]|2[0-4]):?([0-5][0-9]))?$')) {
        tmp_value = parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S%z") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%z") ?? parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S%.f%z") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%.f%z") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%.f %z") ?? parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S") ?? parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S%.f") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%.f") ?? value_string
        if is_string(tmp_value) {
          log("Failed to convert timestamp: " + value_string, level: "warn")
          value
        } else {
          tmp_value
        }
      } else if (tmp_value, err = parse_int(value); err == null) {
        tmp_value
      } else if (tmp_value, err = to_bool(value); err == null) {
        tmp_value
      } else if (tmp_value, err = to_float(value); err == null) {
        tmp_value
      } else {
        value
      }
    }
  '''

[transforms.RECmd_LocalAccounts_dedup_CreatedOn_to_sink]
  type = "remap"
  inputs = ["RECmd_LocalAccounts_coerce"]
  source = '''
    if is_nullish(.createdon) {
      abort
    }

    .timestamp = .createdon
    .operation = "creation"
    .suboperation = "creation_localaccount_createdon"
  '''

[transforms.RECmd_LocalAccounts_dedup_LastLoginTime_to_sink]
  type = "remap"
  inputs = ["RECmd_LocalAccounts_coerce"]
  source = '''
    if is_nullish(.lastlogintime) {
      abort
    }

    .timestamp = .lastlogintime
    .operation = "connection"
    .suboperation = "connection_lastlogintime"
  '''

[transforms.RECmd_LocalAccounts_dedup_LastPasswordChange_to_sink]
  type = "remap"
  inputs = ["RECmd_LocalAccounts_coerce"]
  source = '''
    if is_nullish(.lastpasswordchange) {
      abort
    }

    .timestamp = .lastpasswordchange
    .operation = "modification"
    .suboperation = "modification_lastpasswordchange"
  '''

[transforms.RECmd_LocalAccounts_dedup_LastIncorrectPassword_to_sink]
  type = "remap"
  inputs = ["RECmd_LocalAccounts_coerce"]
  source = '''
    if is_nullish(.lastincorrectpassword) {
      abort
    }

    .timestamp = .lastincorrectpassword
    .operation = "connection"
    .suboperation = "connection_lastincorrectpassword"
  '''

[transforms.RECmd_LocalAccounts_dedup_ExpiresOn_to_sink]
  type = "remap"
  inputs = ["RECmd_LocalAccounts_coerce"]
  source = '''
    if is_nullish(.expireson) {
      abort
    }

    .timestamp = .expireson
    .operation = "expiration"
    .suboperation = "expiration_expireson"
  '''
