# Vector_Windows_EZTools_SBECmd_Shellbags config.
# Description: Process Windows artefacts parsed with SBECmd (CSV output) !through KAPE!.
#              Filename should match: "*/FileFolderAccess/*NTUSER.DAT.csv" and/or "*/FileFolderAccess/*ntuser.dat.csv" and/or "*/FileFolderAccess/*UsrClass.dat.csv"
#              SBECmd command: SBECmd.exe -d %sourceDirectory% --csv %destinationDirectory% -q
#              Example command: SBECmd.exe -d "C:\ --csv <YOUR_OUTPUT> -q
#              source = "windows_shellbags" & sourcetype = "windows_artefact"
# Author(s): Jérôme BREBION, Thomas DIOT (_Qazeer)
# Version: 1.0
# Last modified: 2022-09-28
# Required environment variables:
#   INPUT_FOLDER = "<INPUT_FOLDER>"
#   VECTOR_TEMP_FOLDER = "<VECTOR_TEMP_FOLDER>"
#   SOURCE_HOST = "<SOURCE_HOST>"

# Temporary folder used by Vector.
data_dir = "${VECTOR_TEMP_FOLDER:?A directory for Vector temporary data is required}"

# Set the default timezone to UTC+0 for timestamps that do not include a timezone.
timezone = "Etc/UTC"

[sources.SBECmd_Shellbags_csv_input]
  type = "file"
  include = [
    "${INPUT_FOLDER:?The input folder containing the SBECmd Shellbags NTUSER (uppercase) files is required.}/*/FileFolderAccess/*NTUSER.DAT.csv",
    "${INPUT_FOLDER:?The input folder containing the SBECmd Shellbags ntuser (lowercase) files is required.}/*/FileFolderAccess/*ntuser.dat.csv",
    "${INPUT_FOLDER:?The input folder containing the SBECmd Shellbags NTUSER (uppercase) files is required.}/*/FileFolderAccess/*NTUSER.DAT.csv",
    "${INPUT_FOLDER:?The input folder containing the SBECmd Shellbags ntuser (lowercase) files is required.}/*/FileFolderAccess/*ntuser.dat.csv",
    "${INPUT_FOLDER:?The input folder containing the SBECmd Shellbags ntuser (lowercase) files is required.}/*/FileFolderAccess/*ntuser.csv",
    "${INPUT_FOLDER:?The input folder containing the SBECmd Shellbags NTUSER (uppercase) files is required.}/*/FileFolderAccess/*NTUSER.csv",
    "${INPUT_FOLDER:?The input folder containing the SBECmd Shellbags UsrClass files is required.}/*/FileFolderAccess/*UsrClass.dat.csv",
    "${INPUT_FOLDER:?The input folder containing the SBECmd Shellbags UsrClass files is required.}/*/FileFolderAccess/*UsrClass.csv"
  ]
  ignore_checkpoints = true
  read_from = "beginning"
  oldest_first = false
  glob_minimum_cooldown_ms = 100000
  fingerprint.strategy = "device_and_inode"
  max_line_bytes = 100_000_000
  offset_key = "__offset"

[transforms.SBECmd_Shellbags_csv_parser]
  type = "remap"
  inputs = ["SBECmd_Shellbags_csv_input"]
  source = '''
    # Expect CSV header:
    # BagPath,Slot,NodeSlot,MRUPosition,AbsolutePath,ShellType,Value,ChildBags,CreatedOn,ModifiedOn,AccessedOn,LastWriteTime,MFTEntry,MFTSequenceNumber,ExtensionBlockCount,FirstInteracted,LastInteracted,HasExplored,Miscellaneous
    fields, err = parse_csv(.message, delimiter: ",")
    if err != null {
      log("Unable to split CSV: " + err, level: "error")
    }

    if .__offset == 0 {
      # Special usecase as the header line may (or may not) start with 'M-oM-;M-?' (UTF-8 with BOM).
      expected_header = "BagPath,Slot,NodeSlot,MRUPosition,AbsolutePath,ShellType,Value,ChildBags,CreatedOn,ModifiedOn,AccessedOn,LastWriteTime,MFTEntry,MFTSequenceNumber,ExtensionBlockCount,FirstInteracted,LastInteracted,HasExplored,Miscellaneous"
      current_header = strip_whitespace(to_string!(.message))
      header_find = find(current_header, expected_header)
      if header_find == -1 || (header_find != 0 && header_find != 3) {
        log("Unexpected CSV header, possible non-integrated tool update!\n=> Expected CSV header: " + expected_header + "\n=> Got CSV header:      " + current_header, level: "error")
      }
      abort
    }

    .bagpath = fields[0]
    .mruposition = fields[3]
    .absolutepath = fields[4]
    .shelltype = fields[5]
    .value = fields[6]
    .childbags = fields[7]
    .createdon = fields[8]
    .modifiedon = fields[9]
    .accessedon = fields[10]
    .lastwritetime = fields[11]
    .mftentry = fields[12]
    .firstinteracted = fields[15]
    .lastinteracted = fields[16]

    # Shellbag filename is: Administrator_NTUSER.csv or Administrator_UsrClass.csv
    if (match_user, err = parse_regex(.file, r'.*(\\|/)(?P<username>.*?)_(UsrClass|AppData_Local_Microsoft_Windows_UsrClass|NTUSER|ntuser).*csv'); err == null) {
      .user = match_user.username
    } else {
      .user = ""
    }

    # Add the metadata fields following the parsing.
    .sourcehost = "${SOURCE_HOST:?The source host is required}"
    .host = .sourcehost
    .category = "filefolderaccess"
    .source = "windows_shellbags"
    .sourcetype = "windows_artefact"

    # Delete irrelevant default fields.
    del(.source_type)
    del(.file)
    del(.message)
    del(.__offset)
  '''

[transforms.SBECmd_Shellbags_coerce]
  type = "remap"
  inputs = ["SBECmd_Shellbags_csv_parser"]
  source = '''
    . = map_values(.) -> |value| {
      value_string, convert_err = string(value)
      # Only coerce string (and not already casted types, such as int, timestamps, etc.).
      if convert_err != null {
        value
      # Matches a timestamp in various format ("T" or space separated, with or without post second precision, and with or without a timezone identifier).
      } else if (match(value_string, r'^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[0-1])[T|\s]([01][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9])(\.[0-9]{1,9})?(\s?[\+|\-]([01][0-9]|2[0-4]):?([0-5][0-9]))?$')) {
        tmp_value = parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S%z") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%z") ?? parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S%.f%z") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%.f%z") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%.f %z") ?? parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S") ?? parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S%.f") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%.f") ?? value_string
        if is_string(tmp_value) {
          log("Failed to convert timestamp: " + value_string, level: "warn")
          value
        } else {
          tmp_value
        }
      } else if (tmp_value, err = parse_int(value); err == null) {
        tmp_value
      } else if (tmp_value, err = to_bool(value); err == null) {
        tmp_value
      } else if (tmp_value, err = to_float(value); err == null) {
        tmp_value
      } else {
        value
      }
    }
  '''

[transforms.SBECmd_Shellbags_dedup_LastWriteTime_to_sink]
  type = "remap"
  inputs = ["SBECmd_Shellbags_coerce"]
  source = '''
    if is_nullish(.lastwritetime) {
      abort
    }

    .timestamp = .lastwritetime
    .operation = "modification"
    .suboperation = "modification_lastwritetime"
  '''

[transforms.SBECmd_Shellbags_dedup_CreatedOn_to_sink]
  type = "remap"
  inputs = ["SBECmd_Shellbags_coerce"]
  source = '''
    if is_nullish(.createdon) {
      abort
    }

    .timestamp = .createdon
    .operation = "creation"
    .suboperation = "creation_createdon"
  '''

[transforms.SBECmd_Shellbags_dedup_ModifiedOn_to_sink]
  type = "remap"
  inputs = ["SBECmd_Shellbags_coerce"]
  source = '''
    if is_nullish(.modifiedon) {
      abort
    }

    .timestamp = .modifiedon
    .operation = "modification"
    .suboperation = "modification_modifiedon"
  '''

[transforms.SBECmd_Shellbags_dedup_AccessedOn_to_sink]
  type = "remap"
  inputs = ["SBECmd_Shellbags_coerce"]
  source = '''
    if is_nullish(.accessedon) {
      abort
    }

    .timestamp = .accessedon
    .operation = "access"
    .suboperation = "access_accessedon"
  '''

[transforms.SBECmd_Shellbags_dedup_FirstInteracted_to_sink]
  type = "remap"
  inputs = ["SBECmd_Shellbags_coerce"]
  source = '''
    if is_nullish(.firstinteracted) {
      abort
    }

    .timestamp = .firstinteracted
    .operation = "modification"
    .suboperation = "modification_firstinteracted"
  '''

[transforms.SBECmd_Shellbags_dedup_LastInteracted_to_sink]
  type = "remap"
  inputs = ["SBECmd_Shellbags_coerce"]
  source = '''
    if is_nullish(.lastinteracted) {
      abort
    }

    .timestamp = .lastinteracted
    .operation = "modification"
    .suboperation = "modification_lastinteracted"
  '''
