# Description: Process Windows EVTX parsed as JSON with Winlogbeat.
#              Filename should match: "*winlogbeat*.ndjson"
#              The EVTX can be parsed with Winlogbeat using:
#                - For all events, the Winlogbeat_ALL.mkape KAPE module (https://github.com/EricZimmerman/KapeFiles/blob/master/Modules/Apps/Winlogbeat_ALL.mkape)
#                - For a filtered set of events, the Winlogbeat_Windows_EVTX_to_JSON_filtered.yml configuration file in the present repository.
#              source = "windows_evtx" & sourcetype = "windows_artefact"
# Author(s): Thomas DIOT (_Qazeer)
# Version: 1.0
# Last modified: 2022-09-01
# Required environment variables:
#   INPUT_FOLDER = "<INPUT_FOLDER>"
#   VECTOR_TEMP_FOLDER = "<VECTOR_TEMP_FOLDER>"
#   SOURCE_HOST = "<SOURCE_HOST>"

# Temporary folder used by Vector.
data_dir = "${VECTOR_TEMP_FOLDER:?A directory for Vector temporary data is required}"

# Set the default timezone to UTC+0 for timestamps that do not include a timezone.
timezone = "Etc/UTC"

[sources.Windows_EVTX_winlogbeat_input]
  type = "file"
  include = ["${INPUT_FOLDER:?The input folder containing the Winlogbeat JSON output files is required.}/*/EventLogs/*winlogbeat*.ndjson"]
  ignore_checkpoints = true
  read_from = "beginning"
  oldest_first = false
  glob_minimum_cooldown_ms = 100000
  fingerprint.strategy = "device_and_inode"
  max_line_bytes = 100_000_000

[transforms.Windows_EVTX_winlogbeat_parser_to_sink]
  type = "remap"
  inputs = ["Windows_EVTX_winlogbeat_input"]
  source = '''
    message_parsed, err = parse_json(.message)
    if err != null {
      log("Unable to parse log line: '" + string!(.message) + "'. Error: " + err, level: "error")
      abort
    } else {
      . = message_parsed
    }

    # Rename / remove fields in the ELK format introduced by Winlogbeat.
    if (.timestamp, err = parse_timestamp(.@timestamp, format: "%+"); err != null) {
      log("Unable to convert timestamp: " + err, level: "warn")
    }
    del(.@timestamp)
    del(.@metadata)

    # Flatten the Windows event itself from the "winlog" field.
    ., err |= flatten(.winlog)
    del(.winlog)

    # Add the source host following the parsing.
    if !(exists(.computer_name) && .computer_name != "") {
      log("The log entry does not contain a computer name", level: "warn")
    }

    .sourcehost = "${SOURCE_HOST:?The source host is required}"
    .host = .computer_name
    .category = "evtx_events"
    .source = "windows_evtx"
    .sourcetype = "windows_artefact"
  '''
